{{- range $key, $value := .Values.configMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $key }}
  namespace: {{ $value.namespace }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  annotations:
    {{- include "app.annotations" $ | nindent 4 }}
data:
  {{- toYaml $value.data | trim | nindent 2 }}
{{- end }}
