---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.9.0
  values:
    controller:
      kind: DaemonSet
      tolerations:
        - key: node-role.kubernetes.io/front
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/front: ""
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - ingress-nginx
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - ingress-nginx
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - controller
      admissionWebhooks:
        tolerations:
          - key: node-role.kubernetes.io/front
            effect: NoSchedule
        nodeSelector:
          node-role.kubernetes.io/front: ""
      metrics:
        enabled: true
      service:
        type: NodePort
        nodePorts:
          http: "80"
          https: "443"