apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: zamolodchikov
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: podinfo-dev
  chart:
    git: https://github.com/fluxcd/helm-operator-get-started.git
    path: charts/podinfo
    ref: master
  valuesFrom:
    - configMapKeyRef:
        name: k8s-addons
        namespace: zamolodchikov
        key: values.yaml
        optional: false
    - configMapKeyRef:
        name: k8s-addons-custom
        namespace: zamolodchikov
        key: values.yaml
        optional: true
