---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://charts.helm.sh/stable
    name: prometheus-operator
    version: 6.7.4
values:
  defaultRules:
    create: false
  prometheusOperator:
    enabled: true
    createCustomResource: true
    tolerations:
      - key: node-role.kubernetes.io/system
        effect: NoSchedule
    nodeSelector:
      node-role.kubernetes.io/system: ""
  prometheus:
    enabled: true
    prometheusSpec:
      tolerations:
        - key: node-role.kubernetes.io/system
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/system: ""
  alertmanager:
    enabled: true
    alertmanagerSpec:
      image:
        tag: v0.21.0
      tolerations:
        - key: node-role.kubernetes.io/system
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/system: ""
    config:
      global:
        resolve_timeout: 5m
      receivers:
        - name: "null"
      route:
        group_by:
          - alertname
          - cluster
          - job
        group_interval: 5m
        group_wait: 30s
        receiver: "null"
        repeat_interval: 12h
        routes:
          - match:
              alertname: Watchdog
            receiver: "null"
  grafana:
    enabled: true
    defaultDashboardsEnabled: true
    adminUser: admin
    adminPassword: admin
    tolerations:
      - key: node-role.kubernetes.io/system
        effect: NoSchedule
    nodeSelector:
      node-role.kubernetes.io/system: ""
  kubeApiServer:
    enabled: false
  kubelet:
    enabled: false
  kubeControllerManager:
    enabled: false
  coreDns:
    enabled: false
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false